export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';

// Promise states
export const REQUEST_ROBOTS_PENDING = 'REQUEST_ROBOTS_PENDING'; // waiting for the promise to return
export const REQUEST_ROBOTS_SUCCESS = 'REQUEST_ROBOTS_SUCCESS';
export const REQUEST_ROBOTS_FAILED  = 'REQUEST_ROBOTS_FAILED';